get-categories completed
isamotta/portfolio-be-project pull request #2
Opened 2023-01-16 14:29 UTC by isamotta

2023-01-16 15:03 UTC, NRMSMITH requested changes
Request changes: error handling and catching errors :)

2023-01-16 15:03 UTC, NRMSMITH commented on controllers/categories.js
> +}
How does your controller _catch_ your errors?

2023-01-16 15:03 UTC, NRMSMITH commented on app.js
> +
Error handling middleware can be included here! It would be appropriate to include a 500 error handler here.

2023-01-16 15:21 UTC, isamotta commented on controllers/categories.js
> +}
Added catch block

2023-01-16 15:23 UTC, isamotta commented on app.js
> +
Added middleware function to handle 500 error.

2023-01-16 16:01 UTC, NRMSMITH requested changes
-> Please ensure that your test is checking that you are getting back a message.

2023-01-16 16:01 UTC, NRMSMITH commented on __tests__/app.test.js
> +})
You should be expecting a message saying 'does not exist' here :)  Also 'API' should be 'endpoint'.

2023-01-16 18:23 UTC, isamotta commented on __tests__/app.test.js
> +})
added a message

2023-01-17 10:16 UTC, EddTheDuck approved these changes
Nice job :)

2023-01-17 10:28 UTC, merged